[project]
name = "health-wellness-planner-agent"
version = "0.1.0"
description = "Health_Wellness_Planner_agent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.2",
    "openai-agents>=0.2.2",
    "pymongo>=4.13.2",
    "python-dotenv>=1.1.1",
]
